### PR TITLE
Create Main.cpp

### PR DESCRIPTION
**Pull request by usaotearoa**
Simple subscriber ported from  micro-ROS /micro_ros_arduino/examples to work with teensy and platformio
publishing a 0 to the topic will turn the LED off
publishing a 1 to the topic will turn the LED on

To test this, it can be done from the command line as below:
ros2 topic pub /micro_ros_arduino_subscriber std_msgs/msg/Int32 "data: 1" -1

### CODE REVIEW

**Comment by pablogs9** [comment]
@mergify backport galactic foxy humble

**Comment by pablogs9** [comment]
Please add a [platformio.ini](https://github.com/micro-ROS/micro_ros_platformio/blob/main/examples/micro-ros_publisher/platformio.ini) as in the publisher example

**Comment by usaotearoa** [comment]
Added the platformio.ini.
I wasn't sure if this can be added to this open pull request, so it has been added individually.
Please proceed.

**Comment by usaotearoa** [comment]
Sorry, I'm new to pull requests and github workflow in general. Please excuse silly questions.
What do I need to do here, to make this commit successful?

**Comment by usaotearoa** [comment]
Closed this pull request and opened a new one

**Pull request closed without merging**
